### ISSUE TITLE
Pimatic BMP180 plugin not working with version pimatic 0.9

### ISSUE THREAD

**Issue by free118** [int020h/pimatic-bmp180#1]
hello,
the plugin is not working with version 0.9 of pimatic. 

Please see issue description here:
https://forum.pimatic.org/topic/2097/install-problem-bmp180-plugin-i2c/2

Is it possible to port it to version 0.9?

Thanks
Free

**Comment by int020h** [comment]
Hi, thanks for letting me know. I hadn't updated yet to pimatic 0.9, so I was blissfully unaware of any issues.
When I have time I'll update to 0.9, and see if I can fix the problem with my plugin.
Regards,
int020h

**Comment by int020h** [comment]
Hi, I just published v2.0.1 of the bmp180 plugin that works again with pimatic 0.9.
Please install/update to the new version in pimatic.

**Comment by free118** [comment]
Hi,
i tried the new version and get the following issue:
error [pimatic]: A uncaught exception occured: Error: Error reading length of bytes
    at Error (native)
    at i2c.readBytes (/home/pi/pimatic-app/node_modules/pimatic-bmp180/node_modules/bmp085/node_modules/i2c/lib/i2c.coffee:83:10)
    at [object Object].BMP085.readWord (/home/pi/pimatic-app/node_modules/pimatic-bmp180/node_modules/bmp085/bmp085.js:131:15)
    at /home/pi/pimatic-app/node_modules/pimatic-bmp180/node_modules/bmp085/bmp085.js:156:14
    at Array.forEach (native)
    at [object Object].BMP085.calibrate (/home/pi/pimatic-app/node_modules/pimatic-bmp180/node_modules/bmp085/bmp085.js:155:31)
    at [object Object].BMP085.read (/home/pi/pimatic-app/node_modules/pimatic-bmp180/node_modules/bmp085/bmp085.js:280:10)
    at BMP180Sensor.requestValue (/home/pi/pimatic-app/node_modules/pimatic-bmp180/pimatic-bmp180.coffee:100:15)
    at [object Object]._repeat (/home/pi/pimatic-app/node_modules/pimatic-bmp180/pimatic-bmp180.coffee:93:52)
    at [object Object].wrapper [as _onTimeout] (timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)
 This is most probably a bug in pimatic or in a module, please report it!

But I see the 0x77 if i do i2cdetect -y 1.
Are you able to help?
Thanks
